import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import mjml from "mjml";

const here = dirname(fileURLToPath(import.meta.url));
const emailsDir = join(here, "..", "emails");
const outFile = join(here, "..", "lib", "emails.ts");

const templates = [
  {
    key: "magicLinkHtml",
    file: "magic-link.mjml",
    token: "{{URL}}",
    fn: "renderMagicLink",
    arg: "url",
  },
  { key: "otpHtml", file: "otp.mjml", token: "{{OTP}}", fn: "renderOtp", arg: "otp" },
];

const lines = ["// Generated by scripts/compile-emails.mjs — do not edit by hand.", ""];

for (const { key, file, token, fn, arg } of templates) {
  const source = readFileSync(join(emailsDir, file), "utf8");
  const { html, errors } = await mjml(source, { validationLevel: "soft" });
  if (errors.length > 0) throw new Error(`${file}: ${errors.map((e) => e.message).join("; ")}`);
  lines.push(`const ${key} = ${JSON.stringify(html)};`);
  lines.push(`export function ${fn}({ ${arg} }: { ${arg}: string }): string {`);
  lines.push(`  return ${key}.split(${JSON.stringify(token)}).join(escapeHtml(${arg}));`);
  lines.push(`}`);
  lines.push("");
}

lines.push(`function escapeHtml(value: string): string {`);
lines.push(
  `  const entities: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };`,
);
lines.push(`  return value.replace(/[&<>"']/g, (c) => entities[c]);`);
lines.push(`}`);
lines.push("");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"));
console.log(`Wrote ${outFile}`);
